######################################################################
# Automatically generated by qmake (2.01a) lun. avr. 25 01:03:20 2011
######################################################################

TEMPLATE = app
TARGET = mailme_gui
DEPENDPATH += . 
INCLUDEPATH += . 

# Input
HEADERS += Gui.hpp 
FORMS += interface.ui
SOURCES += Gui.cpp main.cpp ../Mail/Mail.cpp ../Mail/Socket/Socket.cpp ../Mail/Base64/Base64.cpp
